### ISSUE TITLE
Start preheater

### ISSUE THREAD

**Issue by LarsFransson65** [acdcnow/HA_audi_connect_q4#2]
Thanks for setting up this integration, much appreciated!
I would love to be able to start the preheater.
Any ideas if its possible?
Best regards

**Comment by acdcnow** [comment]
That API needs to be rewritten and will maybe not work. Audi is constantly change the API and the endpoint structure so not sure if this will ever work. I do not have any time right now to dig into that. Sorry

**Comment by acdcnow** [comment]
Feature request for sure if there is time
