### ISSUE TITLE
Interference with the original audi connect

### ISSUE THREAD

**Issue by Gollam** [acdcnow/HA_audi_connect_q4#3]
Currently, the original audiconnect and your fork cannot be installed at the same time, because the domain inside the code is the same, for example in manifest.json and const.py. I'd suggest to use a different domain (which should be unique for every integration) to avoid this issue.

**Comment by acdcnow** [comment]
thanks for the suggested solution and it make sense., but you can use as well this integration to add ICE audis should work as well.
If I have time I will start that project.
More interesting is the PPE platform for the Q6 right now with offers such more options.

**Comment by acdcnow** [comment]
Refectoring needed to prevent issue with the ICE integration.
